version: '3.8'

services:
  app:
    build: .
    container_name: surveyapp-api
    ports:
      - "5000:80"
    depends_on:
      - postgres

  postgres:
    image: postgres:13
    container_name: surveyapp-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: surveydb
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  surveyapp.api:
    image: ${DOCKER_REGISTRY-}surveyappapi
    build:
      context: .
      dockerfile: src\SurveyApp.Api\Dockerfile

volumes:
  postgres-data:
